### ISSUE TITLE
További mezők a háziorvosok információi közé

### ISSUE THREAD

**Issue by mdanka** [momentum-mozgalom-tech/mikor-oltanak#5]

**Comment by gergobergo** [comment]
Szerintem fontos lenne előtte, hogy valahogy a meglévő orvos adatbázist tisztítsátok. A listában teljesen kaotikusan vannak a nevek, rendelők telefonszámok. Van ahol egymás mellé kerül a név és a rendelő, máshol csak az orvos neve van.

**Comment by mdanka** [comment]
Azt hiszem érdemes lehetne egyszerűen külön mezőkbe szedni a gyakori adatokat, pl. a telefonszámot és az e-mail-címet

**Comment by gergobergo** [comment]
Lehet még érdemes lenne addig megcsinálni ezt, amíg nincs sok adat, mert szerintem nagy részt kézzel kell ezt átválogatni. Amúgy igen valami ilyen lehetne az interface:
```
export interface IFirestoreSurgery {
    name: string;
    surgeryName?: string; // különválasztani a rendelő nevét
    phone: string;
    email?: string;
    city: string;
    address?: string;
    description?: string;
}
```
Talán még úgy is meg lehet csinálni, hogy minden új paraméter opcionális, és akkor már most be tudod vezetni az új interface-t.

**Comment by mdanka** [comment]
Egyetértek, ez szuper! Igen, én is opcionálisnak tenném meg a mezőket a típusban, de a user interface-en az általad jelölt mezőket kötelezően kitöltendővé tenném.

Ha véletlen van időd egy PR-ra, azt megköszönjük, de ha nem, akkor remélhetőleg hozzájutunk valamikor :)

**Comment by gergobergo** [comment]
@mdanka zárható ez az issue?

**Comment by mdanka** [comment]
Jogos igen :)

**Comment by mdanka** [comment]
@gergobergo Kitettem néhány kapcsolódó változtatást:

- A listában most már megjelennek ezek az új adatok is
- Kereséskor az új mezőkben is keresünk
- Megtisztítottam az eddigi adatokat, ahol szerepelt hely, telefonszám, vagy e-mail-cím, ott azt beleraktam a megfelelő mezőbe
